server:
  port: 8080

spring:
  jackson:
    property-naming-strategy: UPPER_CAMEL_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: ${STORAGE_TIMEZONE:GMT+8}
  datasource:
    url: jdbc:mysql://localhost:3306/jwcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jwcloud